### ISSUE TITLE
Warning if securityGroupIds is not set

### ISSUE THREAD

**Issue by tw1t611** [eddmann/serverless-fargate#19]
Docs show, that securityGroupIds are optional.

```yml
  vpc:
    # (optional) default security groups which are added to tasks that do not contain any overrides; these override any provider-level configuration.
    securityGroupIds:
      - sg-12345
```

Not setting it results in the following error:

```

Warning: Invalid configuration encountered
  at 'provider.vpc': must have required property 'securityGroupIds'

Learn more about configuration validation here: http://slss.io/configuration-validation
```

**Comment by eddmann** [comment]
What configuration are you supplying for the `vpc` configuration at the provider level?

**Comment by tw1t611** [comment]
```
  vpc:
    securityGroupIds:
      - sg-xxx
    subnetIds:
      - subnet-xxx
```

That's what I have for now. Removing `securityGroupIds` causes the warning.
