### ISSUE TITLE
Version 0.0.9 breaks deployment

### ISSUE THREAD

**Issue by johan-smits** [eddmann/serverless-fargate#27]
With `0.0.8` it works but I have updated to `0.0.9` it stopped working:

```
Environment: linux, node 16.17.0, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
At least one of the plugins defines a validation schema that is invalid. Try disabling plugins one by one to identify the problematic plugin and report it to the plugin maintainers.
```

My config:

```yaml
service: xxxxxxx

provider:
  name: aws
  region: eu-west-1
  # (required) similar to Lambda-containers, images defined within the provider are available to tasks.
  ecr:
    images:
      xxxxxxx:
        path: ./
        file: Dockerfile

custom: ${file(serverless/shared.yml):custom_api}
plugins: ${file(serverless/shared.yml):plugins_fargate}

fargate:
  memory: 0.5GB
  cpu: 256
  iamRoleStatements:
    - Effect: Allow
      Action: 'secretsmanager:GetSecretValue'
      Resource: 'arn:aws:secretsmanager:eu-west-1:xxxxx:secret:${opt:stage}/xxxxx-support-*'

  tasks:
    chat-support-bot:
      name: chat-support-bot
      image: chat-support-bot
      vpc:
        subnetIds: ${self:custom.vpc.subnetIdsPublic}
        assignPublicIp: true
      environment:
        RUST_LOG: error
```
