### ISSUE TITLE
The container name needs to be unique per stage.

### ISSUE THREAD

**Issue by sivchand** [eddmann/serverless-fargate#30]
Taking the tasks definitions in serverless.yml
```yaml
...
 tasks:
    mycontainer:
      image: nginx:${env:version}
      cpu: ${param:cpus}
      memory: ${param:memory}
...
```
Assume all the developers share an aws account. and They want to create their own version of the app.

When I do ```sls deploy  --region us-east-1 --stage developer1 ```
results in the json like this
```json
    "ExampleServiceTask": {
      "Type": "AWS::ECS::TaskDefinition",
      "Properties": {
        "ContainerDefinitions": [
          {
            "Name": "mycontainer",
            "Image": "nginx",
         
```
When I do ```sls deploy --region us-east-1 --stage developer2``` 
results in the json like this
```json
    "ExampleServiceTask": {
      "Type": "AWS::ECS::TaskDefinition",
      "Properties": {
        "ContainerDefinitions": [
          {
            "Name": "mycontainer",
            "Image": "nginx",
         
```

Essentially this means if developer2 changes the task parameters and deploys it will deregister the task definition defined by  developer1 which will cause confusion. If I am mistaken please correct me.

**Comment by sivchand** [comment]
I found my mistake. All I had to do is add name to my task def.
```yaml
...
 tasks:
    mycontainer:
      name: mycontainer-${sls:stage}
      image: nginx:${env:version}
      cpu: ${param:cpus}
      memory: ${param:memory}
...
```
