### ISSUE TITLE
Use external image

### ISSUE THREAD

**Issue by georgeboot** [eddmann/serverless-fargate#32]
How would I use an external (docker hub for example) image using this plugin?
Currently, I believe it assumes it should always build the image, but there doesn't seem to be a way to use pre-build images.

**Comment by anujjindal58** [comment]
We are also facing the same issue , did you find any workaround ? @georgeboot.
Any plans @eddmann for the same ?

**Comment by ValeriyaIvanovaPolestar** [comment]
To specify pre-build image from ECR I was able to do it in this way: 
In the provider section : 
```
  ecr:
    images: 
      baseimage:
        # URI of an existing Docker image in ECR
        uri: 1234567890.dkr.ecr.eu-north-1.amazonaws.com/your-repo:yourtag
```

And in the tasks section you specify the baseimage to be used: 
```
  tasks:
    my-task:
      name: my-task-name
      # (required) the task image you wish to run, references images built within the ecr section.
      image: baseimage
```

Of course this is for ECR only, no clue how Dockerhub or else registry can be used with this plugin.
