### ISSUE TITLE
Auto-scale?

### ISSUE THREAD

**Issue by alienself** [eddmann/serverless-fargate#52]
Hi!

Great plugin, would love to integrate it with my project however how can I setup auto-scaling so that the service count increases depending on traffic / cpu usage?

**Comment by LorenzoRogai** [comment]
You can configure it like this (replace YourServiceName):

```
  AutoScalingTarget:
      Type: AWS::ApplicationAutoScaling::ScalableTarget
      Properties:
        MinCapacity: ${param:minCapacity}
        MaxCapacity: ${param:maxCapacity}
        ResourceId: !Join [ "", ["service/", !Select [1, !Split [":service/", !Ref YourServiceNameService]]] ]
        ScalableDimension: ecs:service:DesiredCount
        ServiceNamespace: ecs

    AutoScalingPolicy:
      Type: AWS::ApplicationAutoScaling::ScalingPolicy
      Properties:
        PolicyName: ServiceAutoScalingPolicy
        PolicyType: TargetTrackingScaling
        ScalingTargetId: !Ref AutoScalingTarget
        TargetTrackingScalingPolicyConfiguration:
          PredefinedMetricSpecification:
            PredefinedMetricType: ECSServiceAverageCPUUtilization
          ScaleInCooldown: 10
          ScaleOutCooldown: 10
          TargetValue: 75
```
