### ISSUE TITLE
Enviroment is not passed into the docker

### ISSUE THREAD

**Issue by watislaf** [eddmann/serverless-fargate#59]
Hi. I declared env vars in tasks and in provider section.
```
provider:
  name: aws
  stage: ${opt:stage, 'test'}
  region: us-east-1
  profile: watislaf
  
  environment: # example
    TEST: "HELLO WORLD" 
```
    
and conencted it to an image .

My image simply logs all env vars

RUN env 
RUN someFunctionWithErrorSoICanSeeEnv

When i run serverless print i can see all my wars in config but non of them are passed into a docker container.

I have checked it and the command that is executed when docker is runned :

docker build -t name1:name2 -f pathTo/Dockerfile .

so based on it i am assuming that env vars are not pased into docker during the build since this is how they should be passed https://vsupalov.com/docker-build-pass-environment-variables/ 

My question is it possible to pass env vars into docker build process with this plugin ? Thanks
